<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>uTitle</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <style type="text/css">
      img {border-width: 0}
      * {font-family:'Lucida Grande', sans-serif;}
    </style>
  </head>
  <body>
    <div>
     <div style="width:960px;">
<div style="float:right;"><object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/RVp2F6tDWfw&hl=en&fs=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/RVp2F6tDWfw&hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object></div>
 <h2>Welcome to the prototype YouTube Twitter Timeline Subtitler - uTitle</h2>
<h3>What is uTitle?</h3>
 <p>uTitle is an experimental service, which provides an interface for making and reviewing timeline comments of YouTube videos using Twitter. uTitle integrates with the Twitter Search and the 3rd party archive service Twapper Keeper to aggregate tweets which have a YouTube video ID and timestamp:</p>
 <img src="images/tweet.gif" alt="example tweet">
 <p>Comments made using uTitle can be seen as subtitles during video playback. Users can search comments and jump to the position in the video where they were made. </p>
 <p>Commented videos can be shared with direct links (e.g. 
  <a href="http://www.rsc-ne-scotland.org.uk/mashe/utitle/int.php?v=RVp2F6tDWfw">http://www.rsc-ne-scotland.org.uk/mashe/utitle/int.php?v=RVp2F6tDWfw</a>) </p>
 <h3>Get started </h3>
        <div style="text-align:center"><?php print_r($content); ?></div>
<div style="font-size:80%;"> 
<h4>Credits and disclaimer</h4>
<p>This site was developed by Martin Hawksey (<a href="http://twitter.com/mhawksey">@mhawksey</a>) at the <a href="http://www.rsc-ne-scotland.ac.uk/">JISC RSC Scotland North &amp; East</a>. <a href="http://www.rsc-ne-scotland.org.uk/mashe/2010/06/convergence-youtube-meets-twitter-in-timeline-commenting-of-youtube-videos-using-twitter-utitle/">Read more about its development in this post</a>.  Twitter API integration build with <a href='http://github.com/abraham/twitteroauth'>TwitterOAuth</a> by <a href='http://abrah.am/'>Abraham Williams</a> | Tweet archiving using <a href="http://twapperkeeper.com">Twapper Keeper</a> | Video playback using <a href="http://www.longtailvideo.com/players/jw-flv-player/">JW Player </a></p>
<p>This site is a third party application for <a href="http://twitter.com">Twitter</a> and <a href="http://www.youtube.com">YouTube</a></p>
 
</div>
</div>
	  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-2382132-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </body>
</html>
